arc: decoder: Rename FLOAT instruction class to ARC64_FLOAT
On Windows, FLOAT is defined by a system header (minwindef.h in case of
MinGW) and this results in the following error when building ARC QEMU
for Windows:

    error: ‘FLOAT’ redeclared as different kind of symbol

This commit renames FLOAT to ARC64_FLOAT since it is currently only used
in the ARC64 table.

Signed-off-by: Stephanos Ioannidis <root@stephanos.io>